#!/usr/bin/env python
#
# Copyright 2016-2017 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pipe in binaries.csv from stdin

import sys, csv, subprocess, os, urllib2

version = "1.1.0-SNAPSHOT"
build = sys.argv[1]

root = subprocess.check_output(["git", "rev-parse", "--show-toplevel"]).rstrip()
path = "{}/test/csit/docker".format(root)
url_template = "https://nexus.open-o.org/service/local/artifact/maven/redirect?r=snapshots&g={0}&a={1}&e={2}&c={3}&v=LATEST"

with sys.stdin as f:
    reader = csv.DictReader(f)

    for row in reader:
        if len(sys.argv) < 3 or sys.argv[2]==row["filename"]:
            print row["filename"]

            if row["classifier"]:
                file = "{}-{}-{}.{}".format(row["artifactId"], version, row["classifier"], row["extension"])
                dest = "{}-{}-{}.{}".format(row["filename"], version, row["classifier"], row["extension"])
            else:
                file = "{}-{}.{}".format(row["artifactId"], version, row["extension"])
                dest = "{}-{}.{}".format(row["filename"], version, row["extension"])

            dir = "{}/{}".format(path, row["filename"])

            try:
                os.mkdir(dir)
            except OSError:
                pass

            # create empty Dockerfile if not exists
            dockerfile=open( "{}/Dockerfile".format(dir), "a" )
            dockerfile.close()

            outfile = open( "{}/50-microservice.txt".format(dir), "w" )
            
            # url = "https://nexus.open-o.org/content/repositories/{}/{}/{}/{}/{}".format(build, row["groupId"].replace(".","/"), row["artifactId"], version, file )
            url = url_template.format(row["groupId"], row["artifactId"], row["extension"], row["classifier"])
            response = urllib2.urlopen(url)

            outfile.write("# 50-microservice.txt - AUTOGENERATED, DO NOT MODIFY MANUALLY\n\n")   
            outfile.write("# Set up microservice\n")
            
            outfile.write("RUN wget -q -O {} \"{}\"".format(dest, response.geturl()))
            # outfile.write("ADD \"{}\" {}\n".format(url, dest))

            unzip_opt = ""
            if row["extension"] == "tar.gz":
                if row["unzip-dir"]:
                    unzip_opt = " -C {}".format(row["unzip-dir"])
                outfile.write(" && tar -xf {}{}".format(dest, unzip_opt))
            elif row["extension"] == "zip":
                if row["unzip-dir"]:
                    unzip_opt = " -d {}".format(row["unzip-dir"])
                outfile.write(" && unzip -q -o -B {}{}".format(dest, unzip_opt))
            outfile.write(" && rm -f {}\n".format(dest))
            
            if row["ports"]:
                ports = row["ports"].split()
                for port in ports:
                    outfile.write("EXPOSE {}\n".format(port))
            outfile.write("RUN echo Open-O {} {} \"{}\" > OPENO_VERSION\n".format(row["filename"], version, response.geturl()))
            outfile.write("\n\n")
            
            outfile.close()


            def symlink(flag, template):
                try:
                    os.remove("{}/{}".format(dir, template))
                except OSError:
                    pass
                if flag:
                    os.symlink("../templates/{}".format(template), "{}/{}".format(dir, template))

            symlink(True, "10-basebuild.txt")
            symlink(row["python"], "15-python.txt")
            symlink(row["mysql"], "20-mysql.txt")
            symlink(row["tomcat"], "30-tomcat.txt")
            symlink(True, "90-entrypoint.txt")
