#!/bin/sh

# docker root dir
ROOT=`git rev-parse --show-toplevel`/test/csit/docker

cd $ROOT

$ROOT/scripts/gen-dockerfiles.py < $ROOT/../../../autorelease/binaries.csv


for file in `find -name Dockerfile`; do
    dir=`dirname $file`
    cat > $dir/Dockerfile <<EOF
#
# This file was auto-generated by gen-all-dockerfiles.sh; do not modify manually.
#
# $dir/Dockerfile
#

EOF
    cat $dir/*.txt >> $dir/Dockerfile

    if [ -f $dir/20-mysql.txt ]; then
	cat > $dir/init-mysql.sh <<EOF
#!/bin/bash -v
#
# This file was auto-generated by gen-all-dockerfiles.sh; do not modify manually.
#
# $dir/init-mysql.sh
#

EOF
	cat $ROOT/templates/init-mysql.sh >> $dir/init-mysql.sh
	chmod +x $dir/init-mysql.sh
    else
	rm -f $dir/init-mysql.sh
    fi
done
