#!/bin/bash
#
# Copyright 2016-2017 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# $1 autorelease build

if [ -z "$1" ]; then
    echo $0 "<build>"
    exit 1;
fi

BUILD=$1

# docker root dir
ROOT=`git rev-parse --show-toplevel`/test/csit/docker

cd $ROOT

$ROOT/scripts/gen-dockerfiles.py $BUILD < $ROOT/../../../autorelease/binaries.csv


# Update build number in workaround files
for file in `find -name 80-workaround.txt`; do
    sed -i "s|autorelease-[0-9]\{4\}|$BUILD|" $file
done


for file in `find -name Dockerfile`; do
    dir=`dirname $file`

    cp $ROOT/../../../distribution/LICENSE $dir
    cat > $dir/Dockerfile <<EOF
#
# This file was auto-generated by gen-all-dockerfiles.sh; do not modify manually.
#
# $dir/Dockerfile
#

EOF
    cat $dir/*.txt >> $dir/Dockerfile

    if [ -f $dir/20-mysql.txt ]; then
	cat > $dir/init-mysql.sh <<EOF
#!/bin/bash
#
# Copyright 2016-2017 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# This file was auto-generated by gen-all-dockerfiles.sh; do not modify manually.
#
# $dir/init-mysql.sh
#

EOF
	cat $ROOT/templates/init-mysql.sh >> $dir/init-mysql.sh
    else
	rm -f $dir/init-mysql.sh
    fi

    cat > $dir/docker-entrypoint.sh <<EOF
#!/bin/bash
#
# Copyright 2016-2017 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# This file was auto-generated by gen-all-dockerfiles.sh; do not modify manually.
#
# $dir/docker-entrypoint.sh
#

if [ -z "\$SERVICE_IP" ]; then
    export SERVICE_IP=\`hostname -i\`
fi
echo
echo Environment Variables:
echo "SERVICE_IP=\$SERVICE_IP"

EOF

    if [ `basename $dir` != "common-services-msb" ]; then
	cat >> $dir/docker-entrypoint.sh <<EOF
if [ -z "\$MSB_ADDR" ]; then
    echo "Missing required variable MSB_ADDR: Microservices Service Bus address <ip>:<port>"
    exit 1
fi
echo "MSB_ADDR=\$MSB_ADDR"
echo

# Wait for MSB initialization
echo Wait for MSB initialization
for i in {1..20}; do
    curl -sS -m 1 \$MSB_ADDR > /dev/null && break
    sleep \$i
done

EOF
    fi
    
    cat >> $dir/docker-entrypoint.sh <<EOF
echo

# Configure service based on docker environment variables
./instance-config.sh

EOF
    if [ -f $dir/20-mysql.txt ]; then
	cat >> $dir/docker-entrypoint.sh <<EOF
# Start mysql
su mysql -c /usr/bin/mysqld_safe &

EOF
    fi
    cat >> $dir/docker-entrypoint.sh <<EOF
# Perform one-time config
if [ ! -e init.log ]; then
    # Perform workarounds due to defects in release binary
    ./instance-workaround.sh

EOF
    if [ -f $dir/20-mysql.txt ]; then
	cat >> $dir/docker-entrypoint.sh <<EOF
    # Init mysql; set root password
    ./init-mysql.sh

EOF
    fi
    cat >> $dir/docker-entrypoint.sh <<EOF
    # microservice-specific one-time initialization
    ./instance-init.sh

    date > init.log
fi

# Start the microservice
./instance-run.sh

EOF

    touch $dir/instance-config.sh
    touch $dir/instance-init.sh
    touch $dir/instance-run.sh
    touch $dir/instance-workaround.sh
    chmod +x $dir/*.sh
done
