#!/bin/sh

# autorelease root dir
ROOT=`git rev-parse --show-toplevel`/autorelease
VERSION="1.1.0-SNAPSHOT"

BUILD_DIR=$ROOT/build

mkdir -p $BUILD_DIR
cd $BUILD_DIR

FILE=$BUILD_DIR/pom.xml

cat > $FILE <<EOF
<!-- AUTOGENERATED by generate-pom.sh; DO NOT MODIFY MANUALLY -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.openo.oparent</groupId>
    <artifactId>oparent</artifactId>
    <version>$VERSION</version>
    <relativePath>oparent</relativePath>
  </parent>
  <groupId>org.openo.integration.distribution</groupId>
  <artifactId>openo</artifactId>
  <packaging>pom</packaging>
  <modules>
EOF

while read p; do
    cat >> $FILE <<EOF
    <module>$p</module>
EOF
done < $ROOT/java-projects.txt

cat >> $FILE <<EOF
  </modules>
  <dependencies>
EOF

$ROOT/scripts/generate-binary-deps.py < $ROOT/binaries.csv >> $FILE

cat >> $FILE <<EOF
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <appendAssemblyId>true</appendAssemblyId>
          <descriptors>
            <descriptor>assembly.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
EOF


$ROOT/scripts/generate-assembly.py < $ROOT/binaries.csv > $BUILD_DIR/assembly.xml
